"""Design fixtures only. No game rules or runtime UI are implemented here."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
TOKENS = dict(table='#101D1B', panel='#172825', raised='#223833', text='#F3EBD8', muted='#BECBC3', brass='#D8B875', focus='#A0E7EF', error='#FFB5A4', success='#A9DBC1', edge='#6B877B', ink='#17221E')
(ROOT/'source/tokens.json').write_text(json.dumps(TOKENS,indent=2)+'\n')
def text(s,w=400,size=16,color='text',serif=False): return dict(type='text',text=s,w=w,size=size,color=color,serif=serif)
def button(s,w=208,state='default'): return dict(type='button',text=s,w=w,h=44,state=state)
def tile(rank=2,suit='BAM',state='default',mark=''): return dict(type='tile',rank=str(rank),suit=suit,w=42,h=64,state=state,mark=mark)
def row(*c,w=928,h=None,gap=8): return dict(type='row',children=list(c),w=w,h=h,gap=gap)
def col(*c,w=928,h=None,gap=8): return dict(type='col',children=list(c),w=w,h=h,gap=gap)
def panel(name,*c,w=450,h=348): return dict(type='panel',name=name,children=list(c),w=w,h=h,gap=8)
def heading(s,w=400): return text(s,w,18)
def note(s,w=400): return text(s,w,14,'muted')
def tiles(vals=None,state='default',w=640):
 vals=vals or [(1,'BAM'),(2,'BAM'),(3,'BAM'),(4,'CHR'),(5,'CHR'),(6,'CHR'),(7,'DOT'),(8,'DOT'),(9,'DOT'),('E','HON'),('E','HON'),('E','HON'),('W','HON'),('W','HON')]
 return row(*[tile(v,s,state if i<3 else 'default') for i,(v,s) in enumerate(vals)],w=w,h=68,gap=4)
def card(title,body,state='default',w=296):
 identities={'Reserve':[(1,'BAM'),(2,'BAM'),(3,'BAM')],'Sequence':[(1,'CHR'),(2,'CHR'),(3,'CHR')],'East':[('E','HON')],'White':[('W','HON')],'Bamboo 2':[(2,'BAM')]}
 if title in identities: emblem=tiles(identities[title],w=w-24)
 else: emblem=panel('Item kind',text('CHARACTER' if title=='Harbor reader' else 'RULE BREAKER' if title in ['Open Table','Draw Actions','Reserve Witness'] else 'RELIC',w-50,14,'brass'),w=w-24,h=68)
 c=panel(title,heading(title,w-24),emblem,text(body,w-24),button(('Unavailable' if state=='disabled' else 'Inspect '+title),w-24,state),note('Selected' if state=='selected' else 'Locked' if state=='disabled' else 'Available',w-24),w=w,h=348)
 c['state']=state
 return c
SCREENS=[]
def focus_in(d):
 return d.get('type')=='map' or d.get('state') in ['focused','selectedFocused'] or any(focus_in(c) for c in d.get('children',[]))
def add(slug,title,main,commit='Confirm',state='focused',act=1,status=None,notes='',states=None,back='Back / Cancel',footer_note='Tab / shoulders: focus · Enter / A: accept · Esc / B: back'):
 if status is None:status=f'Act {act} of 2  |  Reserve · Pool Bias  |  Gold 24  |  Refinement 1'
 index=len(SCREENS)+1
 if state=='focused' and focus_in(main):state='default'
 tree=col(row(col(note('FORBIDDEN TABLE',620),text(title,620,26,serif=True),w=620,gap=0),button('Help / Settings',292),w=928,h=48,gap=16),row(note(status,928),w=928,h=32),main,row(button(back,180),note(footer_note,496),button(commit,236,state),w=928,h=44),w=960,h=540,gap=8)
 tree.update(type='screen',pad=16)
 if commit!='Review only':tree['children'][-1]['children'][-1]['role']='commit'
 SCREENS.append(dict(id=f'{index:02d}',slug=slug,title=title,notes=notes,states=states or ['focused','contextual-detail'],width=960,height=540,tree=tree))
add('character','Choose your Character',row(card('Reserve','Bamboo starting bias\nRelic: Reserve Sleeve\nCore: Reserve Ledger','selected'),card('Sequence','Characters starting bias\nRelic: Open Hand\nCore: Sequence Line'),card('Harbor reader','Locked in this profile\nUnlock through the Act 2 Normal Ending.','disabled'),gap=16),commit='Choose Reserve',status='NEW RUN  |  Step 1 of 2 · Character',notes='Three production Characters; locked state is an illustrative initial profile. No portrait asset required.',states=['selected','focused','disabled','contextual-detail'])
add('contract','Choose your Contract',row(panel('Contract choices',heading('Contracts',272),button('Pool Bias · Selected',272,'selectedFocused'),button('Pressure',272),button('Refinement Debt',272),button('Open Ledger · Locked',272,'disabled'),note('4 more entries · scroll ↓',272),w=296),panel('Contract details',heading('Pool Bias',584),text('Risk',584,16,'error'),text('Higher pool composition cost; off-suit tile pool weight: 2',584),text('Reward',584,16,'success'),text('Starting tile bias favors Bamboo',584),text('Build bias: reduced flexibility; favors Bamboo 1 and Bamboo 2.\nYaku signal: General Yaku support.',584),w=616),gap=16),commit='Choose Pool Bias',status='NEW RUN  |  Step 2 of 2 · Contract',notes='Pool Bias is both selected and focused; independent state variants are shown on the component specimen.',states=['focused','selected','disabled','contextual-detail'])
for act in [1,2]:
 add(f'map-act-{act}',f'Act {act} · Choose your path',row(dict(type='map',w=616,h=348,act=act),panel('Node detail',heading('Normal left',272),text('Reachable from Intro',272,16,'success'),text('Encounter identity: unrevealed. Only adjacent nodes can be entered.',272),heading('Your Run',272),text('Reserve · Pool Bias\nGold 24 · Refinement 1',272),button('Inspect Tile Pool',272),note('Topology is visible. Distant identities may remain unrevealed.',272),w=296),gap=16),commit='Enter selected node',act=act,notes='Exact 10-node catalog topology. Reachability in fixture: Intro → Normal left/right. Future nodes are displayed as unavailable; unseen payload labels are withheld.',states=['focused','selected','disabled','contextual-detail'])
def battle(main_title='Hand · 13 tiles',empty=False,right=None,feedback=None,selected=False):
 hand=[heading(main_title,640)]
 hand+=[text('Your Hand is empty. Draw a tile to begin.',640)] if empty else [tiles([(1,'BAM'),(2,'BAM'),(3,'BAM'),(4,'CHR'),(5,'CHR'),(6,'CHR'),(7,'DOT'),(8,'DOT'),(9,'DOT'),('E','HON'),('E','HON'),('E','HON'),('W','HON')],state='selected' if selected else 'default'),note('Hand is formal Yaku progress. Selected instances remain explicit.',640)]
 if empty:hand[0]=heading('Hand · 0 tiles',640)
 left=panel('Battle table',row(col(heading('Pressure sentinel',304),text('Enemy HP 8 / 8',304),w=304),col(text('INTENT · Advance Pressure',328,16,'brass'),text('2 Pressure · resolves at End Turn',328),w=328),w=640,h=62),row(note('Pressure 2 / 10    TP 1    Stability 0    Draw Wall 28',640),w=640,h=24),col(*hand,w=640,h=122),row(col(heading('Reserve',216),note('Empty · capacity from state',216),w=216),col(heading('Discard / Exhaust',416),note('Inspect known zone contents',416),w=416),w=640,h=48),note(feedback or 'Select tiles or a legal Pattern; base identities remain visible.',640),w=668)
 if right is None:right=panel('Battle actions',heading('Your decision',220),button('Draw tile',220,'focused'),button('Partial Settlement',220,'disabled' if empty else 'default'),button('Complete Hand',220,'disabled'),button('Core Technique',220),note('Complete Hand unavailable: no legal interpretation. Inspect for details.',220),w=244)
 return row(left,right,gap=16)
add('battle-empty','Battle · Draw first',battle(empty=True),commit='End Turn',state='default',notes='Empty Hand and Reserve; disabled Settlement has a visible reason. Domain still validates every command.',states=['empty','disabled','focused'])
add('battle-table','Battle · Read the table',battle(),commit='End Turn',state='default',notes='Intent/resources never require overview scrolling; illustrative values, not replay evidence.',states=['focused','selected','contextual-detail'])
add('pattern-settlement','Choose a Pattern',battle(selected=True,right=panel('Pattern inspector',heading('Sequence · selected',220),tiles([(1,'BAM'),(2,'BAM'),(3,'BAM')],state='selected',w=220),text('Consumes these 3 instances.\nPair is not settleable.',220),button('Triplet · East',220),note('Score / combat output: shown after resolution when no existing preview supplies it.',220),w=244)),commit='Settle Sequence',notes='Map candidates to actual instance IDs; do not infer damage or add an evaluator.',states=['selected','focused','contextual-detail'])
add('complete-hand','Complete Hand · Interpretation',row(panel('Interpretation',heading('Standard · 4 Groups + Pair',640),tiles(state='selected'),text('Sequence Bamboo 1–3 · Sequence Characters 4–6\nSequence Dots 7–9 · Triplet East · Pair White',640),text('Formal evaluation uses Hand. Reserve contributes only where an existing Rule Breaker permits it.',640),note('Alternative interpretations are listed when their consequences differ.',640),w=668),panel('Complete Hand details',heading('Commit this Hand?',220),text('Standard interpretation selected. Review its Yaku and consumed tiles.',220),text('Recovery restrictions remain authoritative.',220),note('Resolved score/output is shown after the command; no invented preview values.',220),w=244),gap=16),commit='Settle Complete Hand',notes='Standard interpretation specimen. Seven Pairs uses 7 distinct-definition pairs; Quads may expand physical tile count.',states=['selected','focused','confirmation','contextual-detail'])
add('tile-detail','Tile detail · Reserve / Discard / Swap',row(panel('Tile context',heading('Bamboo 2 · copy 2',424),tiles([(2,'BAM'),(2,'BAM'),(3,'BAM')],state='selected',w=424),text('Base identity: Bamboo 2\nModifier: Flexible Identity\nInterpretation: only within eligible Sequence evaluation',424),text('Reserve and Discard use this exact instance.',424),w=448),panel('Instance actions',heading('After this Draw',432),button('Store in Reserve',432,'focused'),button('Discard selected tile',432),button('Swap with Reserve tile',432),text('Swap opens an explicit Reserve target selector. Every action has a non-drag path.',432),w=456),gap=24),commit='Confirm tile action',notes='Modifier sample is an existing category; identity flexibility is context-sensitive. Actions reflect existing validation.',states=['selected','focused','contextual-detail'])
add('critical-feedback','Battle · Ordered feedback',row(panel('Resolved group receipt',heading('Complete Hand · consumed groups',640),tiles(state='selected'),text('This is the resolved group receipt, not the current Hand. Current phase comes from the accepted command result.',640),text('Complete Hand settled. → Boss enters phase 2. → Victory!',640,16,'success'),note('No damage value is predicted or invented. Inspect the accepted result for score and combat effects.',640),w=668),panel('Feedback receipt',heading('Resolved',220),text('1. Complete Hand settled.\n2. Boss enters phase 2.\n3. Victory!',220,16,'success'),note('Same ordered text in Normal / Fast / Instant. Updated state is already authoritative.',220),button('Inspect result',220),w=244),gap=16),commit='View current phase',state='default',notes='Critical receipt is a presentation fixture; next surface follows actual command result, not a new Continue command.',states=['contextual-detail'])
add('event','Event · Risk bargain',row(panel('Event context',heading('Risk bargain',424),text('A bargain changes the stakes of every later battle.',424),text('Risk: +1 starting Pressure in later battles.\nReward: +2 Gold per victory this Run.',424),note('The choice affects this Run. Review the Risk and Reward before confirming.',424),w=448),panel('Event options',button('Accept bargain',432,'selected'),button('Leave',432,'focused'),heading('Selected option',432),text('Accept: +1 starting Pressure in later battles; +2 Gold per victory this Run.',432),w=456),gap=24),commit='Choose selected option',notes='Copy is structural where source lacks prose; implementation must use actual Event choice labels/effect summaries.',states=['selected','focused','contextual-detail'])
add('event-unavailable','Event · Conditional choice',row(panel('Event context',heading('Tile surgery',424),text('Refinement Tokens: 0. Spending a Token is unavailable.',424),note('Inspect the unavailable choice for its requirements, or leave this Event.',424),w=448),panel('Event choices',button('Spend Token · unavailable',432,'disabled'),text('Requires an available Refinement Token.',432,16,'error'),button('Leave',432,'focused'),w=456),gap=24),commit='Choose available option',notes='Use existing authored alternatives only; these generic fixture labels are not new content.',states=['disabled','focused','contextual-detail'])
for slug,title,names in [('reward-normal','Choose your reward',['East','Bamboo 2','White']),('reward-elite','Elite reward',['Complete Hand Insurance','Reserve Sleeve','Settlement Seal']),('reward-boss','Boss reward · Rule Breaker',['Open Table','Draw Actions','Reserve Witness'])]:
 mechanics={'East':'Honor · East\nBase identity remains visible.','Bamboo 2':'Bamboo · rank 2\nInspect any instance Modifiers.','White':'Honor · White dragon\nInspect any instance Modifiers.','Complete Hand Insurance':'Relic · Gain Stability 2','Reserve Sleeve':'Relic · Reserve capacity +1','Settlement Seal':'Relic · Settlement capacity +1','Open Table':'Rule Breaker · Settlement capacity +1','Draw Actions':'Rule Breaker · Draw capacity +1','Reserve Witness':'Rule Breaker · Reserve capacity +1'}
 main=row(*[card(n,mechanics[n],'selected' if i==0 else 'default') for i,n in enumerate(names)],gap=16)
 add(slug,title,main,commit='Take selected reward',notes='Illustrative draft assembled from existing labels, not a guaranteed offer roster. Preserve current draft semantics; no added skip/reroll.',states=['selected','focused','contextual-detail'])
add('act-transition','Act 1 complete · Act 2 reached',row(panel('Act receipt',text('The Run continues',580,32,serif=True),text('Act 1 Boss defeated\nSelected Rule Breaker acquired\nAct 2 map is now current',580),text('Character, Contract, Tile Pool, build and Run resources carry forward according to the accepted state.',580),note('This receipt overlays the already-resolved Act 2 map. Dismissal does not advance Domain state.',580),w=604),panel('Carried build',heading('Reserve · Pool Bias',284),text('Relics / Techniques\nRule Breakers\nGold / Refinement',284),w=308),gap=16),commit='Dismiss receipt',notes='No new phase, Continue command or artificial state gate.',states=['contextual-detail'])
add('shop','Shop · Compare before you buy',row(panel('Shop offers',row(col(button('Settlement Chart · 10 G',284,'selected'),button('Reserve Sleeve · 12 G',284),button('Bamboo 2 · 5 G',284),w=284),col(button('Settlement Seal · 15 G',284),button('Open Hand · 30 G',284,'disabled'),button('White · 5 G',284),w=284),w=584,gap=16),note('Gold 24 · named offers; inspect before purchase',584),button('Refresh Shop',584),w=608),panel('Offer details',heading('Settlement Chart',280),text('Price 10 Gold\nGold after purchase: 14',280),text('Relic · Settlement Chart\nInspect its rule details before buying.',280),note('Open Hand costs 30 Gold; 6 more required.',280),w=304),gap=16),commit='Buy · 10 Gold',back='Leave Shop',notes='Prices are illustrative. Refresh price/remaining count comes from actual shop state; do not assume it is free.',states=['selected','focused','disabled','contextual-detail'])
add('shop-empty','Shop · No available offers',row(panel('Empty shop',heading('No offers available',580),text('Every current offer is unavailable or sold. Leave Shop to continue along the current route.',580),button('Refresh unavailable',580,'disabled'),note('Refresh availability and remaining count are read from existing Shop state.',580),w=604),panel('Your resources',heading('Gold 24',284),text('No purchase is selected.',284),w=308),gap=16),commit='Leave Shop',notes='Explicit empty and exhausted-refresh state; no automatic free refresh.',states=['empty','disabled','focused'])
add('purchase-confirm','Confirm purchase',row(panel('Purchase review',heading('Settlement Chart',580),text('Cost: 10 Gold\nCurrent Gold: 24\nGold after purchase: 14',580),text('Purchase this existing offer?',580),button('Keep browsing',580,'focused'),w=604),panel('Consequence',heading('Owned build changes',284),text('The item joins your owned build after purchase. Review its rule details before buying.',284),w=308),gap=16),commit='Buy · 10 Gold',state='primary',back='Cancel',notes='Local confirmation only; safest initial focus is Cancel. Domain revalidates offer and funds.',states=['confirmation','focused','contextual-detail'])
add('workshop-services','Workshop · Choose a service',row(panel('Service list',button('Remove',424),button('Transform',424,'focused'),button('Add Modifier',424),button('Replace Modifier',424),button('Duplicate',424),note('Refinement service when available · scroll ↓',424),w=448),panel('Service detail',heading('Transform',432),text('1. Choose an exact tile\n2. Choose a legal result\n3. Review cost and confirm',432),text('Select a service to inspect its available targets and cost.',432),w=456),gap=24),commit='Choose Transform',back='Leave Workshop',notes='All six existing service families are described; only services currently available are enabled.',states=['focused','disabled','contextual-detail'])
add('workshop-target','Workshop · Choose the tile',row(panel('Run Tile Pool',heading('Transform · Step 1',640),tiles(state='selected'),text('Selected: Bamboo 2 · copy 2\nAll duplicate instances remain separately reachable.',640),button('Inspect selected tile',640),note('Long pools use multiple rows or a scrollable grid, with visible row count and focus.',640),w=668),panel('Target detail',heading('Bamboo 2 · copy 2',220),text('Base identity: Bamboo 2\nModifiers: none\nContamination: none',220),note('Choosing a tile does not change the Tile Pool.',220),w=244),gap=16),commit='Select target',notes='Target identity remains stable as focus moves or values change.',states=['selected','focused','contextual-detail'])
add('workshop-value','Workshop · Choose the result',row(panel('Before / After',heading('Transform · Step 2',424),row(tile(1,'BAM'),text('→',32,26,'brass'),tile(2,'BAM','selected'),w=424,h=68),text('Bamboo 1 · copy 1 → Bamboo 2\nPrice: 10 Gold\nGold 24 → 14',424),note('Inspect the resulting tile and its Modifiers before confirming.',424),w=448),panel('Legal results',button('Bamboo 2',432,'selectedFocused'),button('Bamboo 3',432),button('Characters 2',432),text('These results are available for the selected tile. Review the cost before applying.',432),w=456),gap=24),commit='Review Transform',notes='Before/after/cost in one place; final local confirmation does not add a Domain command.',states=['selected','focused','contextual-detail'])
add('workshop-confirm','Confirm Workshop change',row(panel('Change review',heading('Transform this TileInstance?',580),row(tile(1,'BAM'),text('→',32,26,'brass'),tile(2,'BAM','selected'),w=580,h=68),text('Bamboo 1 · copy 1 → Bamboo 2\nPay 10 Gold · balance becomes 14',580),button('Keep choosing',580,'focused'),w=604),panel('Commit guidance',heading('One permanent Run change',284),text('Confirm to apply this change. Cancel returns to the selected tile and result.',284),w=308),gap=16),commit='Transform · 10 Gold',state='primary',back='Cancel',notes='Initial focus Cancel; no optimistic currency or pool mutation.',states=['confirmation','focused'])
add('tutorial','Battle · Tutorial enabled',battle(right=panel('Tutorial callout',heading('Draw and settle',220),text('Draw a tile, choose a legal Pattern, then settle it.',220),button('Draw tile',220,'focused'),button('Disable tutorial',220),button('Reset tutorial',220,'disabled'),note('Reset unavailable: no progress yet. Help is always available.',220),w=244)),commit='End Turn',state='default',notes='All five existing tutorial steps are mapped in interaction notes.',states=['focused','disabled','contextual-detail'])
add('help','Help · Pattern and input reference',row(panel('Rules at the table',heading('Patterns',580),text('Sequence: same suit, three consecutive ranks.\nTriplet: three identical TileDefinitions.\nQuad: four identical TileDefinitions.\nPair: structural; not independently settleable.',580),text('Complete Hand: 4 Groups + Pair, or Seven Pairs. Quads can increase physical tile count.',580),note('Reserve is potential Yaku progress unless an existing Rule Breaker permits official participation.',580),w=604),panel('Controls',heading('Mouse / keyboard / controller',284),text('Click or Enter / A: select\nTab / shoulders: focus\nArrows / D-pad: navigate\nEsc / B: cancel/back',284),button('Close Help',284,'focused'),w=308),gap=16),commit='Close Help',back='Back',notes='Help closes to original control and never submits a game command.',states=['focused','contextual-detail'])
add('settings','Settings · Presentation',row(panel('Feedback mode',heading('Presentation speed',424),button('Normal · selected',424,'selected'),button('Fast',424,'focused'),button('Instant',424),text('All modes preserve readable Complete Hand, Boss transition and victory feedback.',424),w=448),panel('Tutorial settings',heading('Tutorial',432),button('Disable tutorial',432),button('Reset tutorial',432),text('Enable or disable guidance. Reset restarts the tutorial from its first step.',432),note('Help remains available with the tutorial disabled.',432),w=456),gap=24),commit='Close Settings',notes='Local settings overlay proposed; Normal/Fast/Instant controls require no rule change.',states=['selected','focused','disabled','contextual-detail'])
for slug,title,missing in [('summary-victory','Victory · Your Build Story',False),('summary-defeat','Defeat · Pressure limit reached',False),('summary-legacy','Run Summary · Older record',True)]:
 add(slug,title,row(panel('Build story',heading('Reserve · Pool Bias',580),text(('Acts/Bosses: not tracked\nDuration: not tracked' if missing else 'Acts: 2 of 2 · Boss progress from record\nSeed 57002 · Duration from recorded start time'),580),text(('Yaku / Patterns / Complete Hands / maximum Score: not tracked' if missing else 'Core Yaku: none recorded\nCommon Patterns: none recorded\nComplete Hands: 0 · maximum Mahjong Score: 0'),580),text('Relics: Reserve Sleeve, Settlement Seal\nTechnique: Reserve Ledger\nRule Breakers: Open Table, Draw Actions',580),note('Final Tile Pool and milestones · inspect / scroll ↓',580),w=604),panel('Outcome',heading('Result and reason',284),text('Victory' if slug=='summary-victory' else ('Saved result' if missing else 'Defeat: Pressure Limit'),284,24,'success' if slug=='summary-victory' else 'text'),text('Review your final build and milestones below.',284),button('Inspect final Tile Pool',284),w=308),gap=16),commit='Finish Run',back='Inspect build',act=2,notes='Never invent duration or stats for older saves. Snapshot outcome controls the result; fixtures are not a completed real Run.',states=['focused','empty' if missing else 'contextual-detail'])
add('run-complete','Run complete',row(panel('Completed Run',text('The table is quiet',580,32,serif=True),text('Run recorded. The Act 2 Normal Ending unlocks Harbor reader and additional Contracts.',580),text('Review the final Build Story before starting again.',580),button('Inspect Build Story',580),w=604),panel('Next Run',heading('Ready when you are',284),text('New Run returns to Character selection. No revive or new progression system is added.',284),w=308),gap=16),commit='New Run',act=2,notes='New Run gets guaranteed visible initial focus.',states=['focused','contextual-detail'])
add('resume','Welcome back · Suspended Run',row(panel('Suspend Save',heading('Resume your Run',580),text('Act 1 of 2 · Workshop\nReserve · Pool Bias',580),text('Resume continues the saved authoritative state. New Run requires a leave-save confirmation.',580),button('Resume Run',580,'focused'),w=604),panel('Start again',heading('New Run',284),text('Start again from Character selection. Confirm before leaving this saved Run.',284),w=308),gap=16),commit='New Run…',state='default',status='SUSPEND SAVE  |  Compatible save',notes='No fake autosave guarantee. Preserve existing compatibility/load contracts.',states=['focused','confirmation'])
add('save-error','Save recovery · Action required',row(panel('Recovery explanation',heading('This Run could not be resumed',580),text('The Suspend Save commit was interrupted. No older save was loaded. Recovery sources remain unchanged.',580,16,'error'),text('Choose New Run only if you want to leave this save behind. Recovery location remains available in Details.',580),button('View recovery details',580,'focused'),w=604),panel('Safe choices',heading('Preservation pending',284),text('Recovery could not preserve the source. New Run is unavailable until recovery is safe.',284),button('New Run unavailable',284,'disabled'),w=308),gap=16),commit='New Run unavailable',state='disabled',status='SAVE RECOVERY  |  Preserve current sources',notes='Same UI template covers content validation, incompatible save and profile recovery, but actions remain governed by their existing outcomes.',states=['error','disabled','focused','contextual-detail'])
add('abandon-confirm','Leave this Suspend Save?',row(panel('Confirmation',heading('Start a New Run?',580),text('This leaves the current suspended Run behind. The existing save handling decides when a new snapshot replaces it.',580),button('Return to Resume',580,'focused'),w=604),panel('Consequence',heading('Current Run',284),text('Reserve · Pool Bias\nAct 1 of 2 · current suspended Run',284),w=308),gap=16),commit='Start New Run',state='primary',status='SUSPEND SAVE  |  Confirmation',back='Cancel',notes='No new abandon-Run Domain system; this confirms the existing startup New Run choice.',states=['confirmation','focused'])
add('action-error','Workshop · Change rejected',row(panel('Retained selection',heading('Transform was not applied',580),row(tile(1,'BAM'),text('→',32,26,'brass'),tile(2,'BAM','selected'),w=580,h=68),text('Insufficient Gold. Actual cost and available balance are shown from the rejected command context.',580,16,'error'),text('Tile Pool and currency are unchanged for this rejected action.',580),w=604),panel('Recovery',heading('Choose another result',284),text('Try another choice, or return to the service list.',284),button('Back to choices',284,'focused'),w=308),gap=16),commit='Return to choices',notes='Error is adjacent to attempted action, not a timer-only toast. Save-write failure after an accepted action uses a separate success-with-warning receipt.',states=['error','focused','selected'])
add('state-specimens','Component states · Focus is independent',row(panel('Button and choice states',button('Default',424),button('Primary',424,'primary'),button('Focused',424,'focused'),button('Selected',424,'selected'),button('Selected + focused',424,'selectedFocused'),button('Unavailable · needs TP',424,'disabled'),w=448),panel('Tile and feedback states',tiles([(2,'BAM'),(2,'DOT'),(2,'CHR'),('E','HON')],w=432),tiles([(2,'BAM'),(2,'BAM'),(2,'BAM')],state='selected',w=432),text('Success: action accepted',432,16,'success'),text('Error: action rejected',432,16,'error'),text('Empty: no eligible Pattern\nContext: exact tile identity and rule',432),w=456),gap=24),commit='Review only',state='default',status='DESIGN COMPONENTS  |  All states are proposals',notes='Brass inner edge is selection; cyan perimeter is focus. Both may appear together.',states=['focused','selected','disabled','empty','error','contextual-detail'])
# Expansion specimen uses actual longest-source recovery copy, reflows to a full-width detail surface.
add('pseudo-expansion','Pseudo-localization · Expanded recovery',panel('Expanded localized message',heading('[Ŕéçövérý éxþļåñåţîöñ +30%]',904),text('[Ţhé Šüšþéñð Šåvé çömmîţ ŵåš îñţérrüþţéð (SUSPEND_COMMIT_INTERRUPTED). Ñö öļðér šåvé ŵåš ļöåðéð. Ŕéçövérý šöürçéš rémåîñ üñçhåñgéð åñð åré çöþîéð ţö ţhé réçövérý ļöçåţîöñ. Çhööšé Ñéŵ Ŕüñ öñļý îf ýöü ŵåñţ ţö ļéåvé ţhîš šåvé béhîñð. ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]',904),text('Actual longest cases: UI_RUN_SCENE_0012 (186 → 301 observed characters), UI_RUN_CONTROLLER_0001 (175 → 268). Preserve interpolation placeholders and recovery paths.',904),button('View recovery location',440,'focused'),note('Visible buttons wrap; message scrolls independently if expanded further.',904),w=928),commit='Cancel / Return',status='DESIGN STRESS SPECIMEN  |  960×540 · +30% expansion',notes='Illustrative pseudo text; actual Godot pseudo-localization must be rerun after approved implementation.',states=['error','focused','contextual-detail'])

# Presentation fixture selection uses one unambiguous duplicated tile.
target=next(s for s in SCREENS if s['slug']=='workshop-target')
tray=target['tree']['children'][2]['children'][0]['children'][1]
tray['children']=tiles([(1,'BAM'),(2,'BAM'),(2,'BAM'),(3,'BAM'),(4,'CHR'),(5,'CHR'),(6,'CHR'),(7,'DOT'),(8,'DOT'),(9,'DOT'),('E','HON'),('E','HON'),('W','HON'),('W','HON')])['children']
tray['children'][2]['state']='selectedFocused'
tray['children'][2]['instanceLabel']='copy 2'
target['tree']['children'][-1]['children'][-1]['state']='default'
for item in SCREENS:
 if item['slug'] in ['summary-victory','summary-defeat']:
  story=item['tree']['children'][2]['children'][0]
  story['children'][1]=row(panel('Act progress',note('Acts reached',164),heading('2 / 2',164),w=188,h=80),panel('Run seed',note('Seed',164),heading('57002',164),w=188,h=80),panel('Recorded duration',note('Duration',164),heading('18m 24s',164),w=188,h=80),w=580,h=80,gap=8)
  item['notes']+=' Duration is an illustrative recorded-value fixture; older records show not tracked.'

(ROOT/'source/screens.json').write_text(json.dumps(SCREENS,ensure_ascii=False,indent=2)+'\n')
(ROOT/'screen_manifest.json').write_text(json.dumps([dict((k,s[k]) for k in ['id','slug','title','notes','states','width','height']) for s in SCREENS],ensure_ascii=False,indent=2)+'\n')
print(len(SCREENS),'design screens')

ledger_path=ROOT/'source/figma_ledger.json'
if ledger_path.exists():
 (ROOT/'source/review_data.js').write_text('window.FT_REVIEW='+json.dumps({'screens':SCREENS,'ledger':json.loads(ledger_path.read_text())},ensure_ascii=False)+';\n')
